[src]
include = ["manim_voiceover"]

[terminal]
error-on-warning = true

[analysis]
respect-type-ignore-comments = false

[rules]
missing-type-argument = "error"
possibly-missing-attribute = "error"
possibly-unresolved-reference = "error"
possibly-missing-import = "error"
